app:
  DEBUG: true
  LOG_LEVEL: "debug"
  LOG_FILE_LEVEL: "debug"
  PROJECT_NAME: "BioScopeAI Core"
  PROJECT_VERSION: "0.0.1"
  BACKEND_CORS_ORIGINS: ""
  UVICORN_ADDRESS: "0.0.0.0"
  UVICORN_PORT: 8000

database:
  POSTGRES_USER: "example"
  POSTGRES_PASSWORD: "example"
  POSTGRES_SERVER: "example"
  POSTGRES_PORT: 5432
  POSTGRES_DB: "example"

sentry:
  SENTRY_DSN: ""
